ENH: Load combined scale and translation transforms to generated PVs
BrownBiomechanics/SlicerAutoscoperM pull request #139
Opened 2024-11-05 20:14 UTC by sbelsk

Closes https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/133

To reduce clutter for the app users, after the generation of partial volumes in the pre-processing module, only the combined scale and translation transformation layer is loaded and applied onto each PV, instead of the two separate scale and translation trasnforms. I.e., `{}.tfm` is loaded and applied instead of `{}_t.ftm` and `{}_scale.tfm`.

All files are still written to the output directory as part of the PV generation proceess as before.

2024-11-11 16:44 UTC, amymmorton approved these changes
![image](https://github.com/user-attachments/assets/840b91dc-1d26-4aa0-b71e-34ec83231404)


Looks great 
Tested with [BN00124 ](https://drive.google.com/file/d/14dLK307oG974zeKsuA2J2YQWB6nvwJ3n/view?usp=drive_link)

2024-11-11 17:06 UTC, jcfr requested changes
This will definitely be helpful to reduce the "clutter" and help the user work with the set of loaded transform :100: 

After addressing some minor nitpicks, this will be good for integration :pray:

2024-11-11 17:06 UTC, jcfr commented on AutoscoperM/AutoscoperM.py
> +                transformFileName = os.path.join(mainOutputDir, transformSubDir, f"{nodeName}.tfm")
I suggest to keep the check ensuring that `{nodeName}_scale.tfm` and `{nodeName}_t.tfm`

```python
                translationTransformFileName = os.path.join(mainOutputDir, transformSubDir, f"{nodeName}_t.tfm")
                if not os.path.exists(translationTransformFileName):
                    raise ValueError(
                        f"Failed to load partial volume {nodeName}: "
                        "Corresponding translation transform file {translationTransformFileName} not found"
                    )

                scaleTranformFileName = os.path.join(mainOutputDir, transformSubDir, f"{nodeName}_scale.tfm")
                if not os.path.exists(scaleTranformFileName):
                    raise ValueError(
                        f"Failed to load partial volume {nodeName}: "
                        "Corresponding scaling transform file {scaleTranformFileName} not found"
                    )
```

2024-11-11 17:06 UTC, jcfr commented on AutoscoperM/AutoscoperM.py
> +                        "Corresponding translation transform file {transformFileName} not found"
```suggestion
                        "Corresponding combined transform file {transformFileName} not found"
```

2024-11-20 00:46 UTC, jcfr approved these changes

2024-11-20 00:47 UTC, jcfr approved these changes

2024-11-20 00:48 UTC, merged