Update launcher paths for Autoscoper
BrownBiomechanics/SlicerAutoscoperM pull request #29
Opened 2023-06-06 13:59 UTC by NicerNewerCar

* Add `Autoscoper.exe`, `Glew lib`, and `Tiff lib` to `Autoscoper_LIBRARY_PATHS_LAUNCHER_BUILD`
    * This fixes the issue with `shutil.which` not being able to find Autoscoper when built from source. 
* Closes #28

2023-06-06 16:55 UTC, amymmorton commented
Yes. Fixed.  Autoscoper launches- please merge so I can test sample data (not visible on the pull request )

2023-06-06 21:44 UTC, jcfr requested changes

2023-06-06 21:44 UTC, jcfr commented on SuperBuild/External_Autoscoper.cmake
> +
```suggestion
  #-----------------------------------------------------------------------------
  # Launcher setting specific to build tree

  # library paths
  set(${proj}_LIBRARY_PATHS_LAUNCHER_BUILD
    ${EP_BINARY_DIR}/Autoscoper-build/bin/$<CONFIG> # Autoscoper executable
    ${EP_BINARY_DIR}/GLEW-Install/${Slicer_THIRDPARTY_BIN_DIR} # Glew library
    ${EP_BINARY_DIR}/TIFF-Install/${Slicer_THIRDPARTY_BIN_DIR} # TIFF library
    )

  #-----------------------------------------------------------------------------
  # Launcher setting specific to install tree
  
  # NA
```

This should allows the settings to be correct across platform and avoid hard-coding directory name.

2023-06-06 22:38 UTC, jcfr commented
Generated file on Windows:

![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/219043/e98d2fb4-b8fb-4d70-a315-649bd4233365)

2023-06-06 22:40 UTC, jcfr approved these changes

2023-06-06 22:42 UTC, jcfr commented
I tested, and attempting to launcher the application on both Linux and Windows work :heavy_check_mark: 

On Windows, I observed the following error, but this is related to network parameter:

```
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

2023-06-06 22:44 UTC, jcfr commented
```
>>> import shutil 
>>> executablePath = shutil.which("autoscoper") 
>>> print(executablePath)
D:/D/P/S-0-E-b/SlicerAutoscoperM-build/Autoscoper-build/Autoscoper-build/bin/Release\autoscoper.EXE
```

2023-06-06 22:44 UTC, merged

2023-06-08 02:52 UTC, jcfr commented
To follow up this, I was able to test the latest version, and here the message I got the "factory":

![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/219043/56e3aabe-16ad-4395-9bfd-e391d8a215ac)

... it turns out that also missing this one:

![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/219043/562f2a86-69f4-4fe0-a167-3029d7afdebe)

2023-06-08 02:57 UTC, jcfr commented
| Setting Update | Successful Autoscoper Start |
|--|--| 
| ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/219043/6a190702-3c37-4971-96a9-e92b093ddc36) | ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/219043/984eaaed-1aac-4ac8-ab55-86e68d8c11c4) |

2023-06-08 03:06 UTC, jcfr commented
Related pull request:
* https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/31